# Project: Billing System
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main/main.o Recourse/Menu.o
LINKOBJ  = main/main.o Recourse/Menu.o
LIBS     = -L"C:/Installer/Dev-Cpp/TDM-GCC-64/lib" -L"C:/Installer/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Installer/Dev-Cpp/TDM-GCC-64/include" -I"C:/Installer/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Installer/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/Installer/Dev-Cpp/TDM-GCC-64/include" -I"C:/Installer/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Installer/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Installer/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = "Billing System.exe"
CXXFLAGS = $(CXXINCS) -std=c++11 -g3
CFLAGS   = $(INCS) -std=c++11 -g3
DEL      = C:\Installer\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main/main.o: main/main.cpp
	$(CPP) -c main/main.cpp -o main/main.o $(CXXFLAGS)

Recourse/Menu.o: Recourse/Menu.cpp
	$(CPP) -c Recourse/Menu.cpp -o Recourse/Menu.o $(CXXFLAGS)
